<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArrondissementSeeder extends Seeder
{
    public function run(): void
    {
        \App\Models\Arrondissement::insert([
    ['name' => 'Banikoara', 'commune_id' => 1],
    ['name' => 'Founougo', 'commune_id' => 1],
    ['name' => 'Gomparou', 'commune_id' => 1],
    ['name' => 'Goumori', 'commune_id' => 1],
    ['name' => 'Kokey', 'commune_id' => 1],
    ['name' => 'Kokiborou', 'commune_id' => 1],
    ['name' => 'Ounet', 'commune_id' => 1],
    ['name' => 'Sompérékou', 'commune_id' => 1],
    ['name' => 'Soroko', 'commune_id' => 1],
    ['name' => 'Toura', 'commune_id' => 1],
    ['name' => 'Bagou', 'commune_id' => 2],
    ['name' => 'Gogounou', 'commune_id' => 2],
    ['name' => 'Gounarou', 'commune_id' => 2],
    ['name' => 'Ouara', 'commune_id' => 2],
    ['name' => 'Sori', 'commune_id' => 2],
    ['name' => 'Zoungou-Pantrossi', 'commune_id' => 2],
    ['name' => 'Angaradébou', 'commune_id' => 3],
    ['name' => 'Bensékou', 'commune_id' => 3],
    ['name' => 'Donwari', 'commune_id' => 3],
    ['name' => 'Kandi I', 'commune_id' => 3],
    ['name' => 'Kandi II', 'commune_id' => 3],
    ['name' => 'Kandi III', 'commune_id' => 3],
    ['name' => 'Kassakou', 'commune_id' => 3],
    ['name' => 'Saah', 'commune_id' => 3],
    ['name' => 'Sam', 'commune_id' => 3],
    ['name' => 'Sonsoro', 'commune_id' => 3],
    ['name' => 'Birni Lafia', 'commune_id' => 4],
    ['name' => 'Bogo-Bogo', 'commune_id' => 4],
    ['name' => 'Karimama', 'commune_id' => 4],
    ['name' => 'Kompa', 'commune_id' => 4],
    ['name' => 'Monsey', 'commune_id' => 4],
    ['name' => 'Garou', 'commune_id' => 5],
    ['name' => 'Guéné', 'commune_id' => 5],
    ['name' => 'Malanville', 'commune_id' => 5],
    ['name' => 'Madécali', 'commune_id' => 5],
    ['name' => 'Toumboutou', 'commune_id' => 5],
    ['name' => 'Libantè', 'commune_id' => 6],
    ['name' => 'Liboussou', 'commune_id' => 6],
    ['name' => 'Lougou', 'commune_id' => 6],
    ['name' => 'Segbana', 'commune_id' => 6],
    ['name' => 'Sokotindji', 'commune_id' => 6],
    ['name' => 'Boukoumbé', 'commune_id' => 7],
    ['name' => 'Dipoli', 'commune_id' => 7],
    ['name' => 'Korontière', 'commune_id' => 7],
    ['name' => 'Kossoucoingou', 'commune_id' => 7],
    ['name' => 'Manta', 'commune_id' => 7],
    ['name' => 'Natta', 'commune_id' => 7],
    ['name' => 'Tabota', 'commune_id' => 7],
    ['name' => 'Cobly', 'commune_id' => 8],
    ['name' => 'Datori', 'commune_id' => 8],
    ['name' => 'Kountori', 'commune_id' => 8],
    ['name' => 'Tapoga', 'commune_id' => 8],
    ['name' => 'Brignamaro', 'commune_id' => 9],
    ['name' => 'Firou', 'commune_id' => 9],
    ['name' => 'Kérou', 'commune_id' => 9],
    ['name' => 'Koabagou', 'commune_id' => 9],
    ['name' => 'Birni', 'commune_id' => 10],
    ['name' => 'Chabi-Couma', 'commune_id' => 10],
    ['name' => 'Fô-Tancé', 'commune_id' => 10],
    ['name' => 'Guilmaro', 'commune_id' => 10],
    ['name' => 'Kouandé', 'commune_id' => 10],
    ['name' => 'Oroukayo', 'commune_id' => 10],
    ['name' => 'Dassari', 'commune_id' => 11],
    ['name' => 'Gouandé', 'commune_id' => 11],
    ['name' => 'Matéri', 'commune_id' => 11],
    ['name' => 'Nodi', 'commune_id' => 11],
    ['name' => 'Tantéga', 'commune_id' => 11],
    ['name' => 'Tchianhoun-Cossi', 'commune_id' => 11],
    ['name' => 'Kotopounga', 'commune_id' => 12],
    ['name' => 'Kouaba', 'commune_id' => 12],
    ['name' => 'Koundata', 'commune_id' => 12],
    ['name' => 'Natitingou I', 'commune_id' => 12],
    ['name' => 'Natitingou II', 'commune_id' => 12],
    ['name' => 'Natitingou III', 'commune_id' => 12],
    ['name' => 'Natitingou IV', 'commune_id' => 12],
    ['name' => 'Perma', 'commune_id' => 12],
    ['name' => 'Tchoumi-Tchoumi', 'commune_id' => 12],
    ['name' => 'Gnémasson', 'commune_id' => 13],
    ['name' => 'Péhunco', 'commune_id' => 13],
    ['name' => 'Tobré', 'commune_id' => 13],
    ['name' => 'Cotiakou', 'commune_id' => 14],
    ['name' => 'N\'Dahonta', 'commune_id' => 14],
    ['name' => 'Taiakou', 'commune_id' => 14],
    ['name' => 'Tanguiéta', 'commune_id' => 14],
    ['name' => 'Tanongou', 'commune_id' => 14],
    ['name' => 'Kouarfa', 'commune_id' => 15],
    ['name' => 'Tampégré', 'commune_id' => 15],
    ['name' => 'Toucountouna', 'commune_id' => 15],
    ['name' => 'Abomey-Calavi', 'commune_id' => 16],
    ['name' => 'Akassato', 'commune_id' => 16],
    ['name' => 'Godomey', 'commune_id' => 16],
    ['name' => 'Glo-Djigbé', 'commune_id' => 16],
    ['name' => 'Hêvié', 'commune_id' => 16],
    ['name' => 'Kpanroun', 'commune_id' => 16],
    ['name' => 'Ouèdo', 'commune_id' => 16],
    ['name' => 'Togba', 'commune_id' => 16],
    ['name' => 'Zinvié', 'commune_id' => 16],
    ['name' => 'Agbanou', 'commune_id' => 17],
    ['name' => 'Ahouannonzoun', 'commune_id' => 17],
    ['name' => 'Allada', 'commune_id' => 17],
    ['name' => 'Attogon', 'commune_id' => 17],
    ['name' => 'Avakpa', 'commune_id' => 17],
    ['name' => 'Ayou', 'commune_id' => 17],
    ['name' => 'Hinvi', 'commune_id' => 17],
    ['name' => 'Lissègazoun', 'commune_id' => 17],
    ['name' => 'Lon-Agonmey', 'commune_id' => 17],
    ['name' => 'Sekou', 'commune_id' => 17],
    ['name' => 'Togoudo', 'commune_id' => 17],
    ['name' => 'Tokpa-Avagoudo', 'commune_id' => 17],
    ['name' => 'Aganmalomè', 'commune_id' => 18],
    ['name' => 'Agbanto', 'commune_id' => 18],
    ['name' => 'Agonkanmè', 'commune_id' => 18],
    ['name' => 'Dédomè', 'commune_id' => 18],
    ['name' => 'Dékanmè', 'commune_id' => 18],
    ['name' => 'Kpomassè', 'commune_id' => 18],
    ['name' => 'Sègbèya', 'commune_id' => 18],
    ['name' => 'Sègbohouè', 'commune_id' => 18],
    ['name' => 'Tokpa-Domè', 'commune_id' => 18],
    ['name' => 'Avlékété', 'commune_id' => 19],
    ['name' => 'Djègbadji', 'commune_id' => 19],
    ['name' => 'Gakpé', 'commune_id' => 19],
    ['name' => 'Houakpè-Daho', 'commune_id' => 19],
    ['name' => 'Ouidah I', 'commune_id' => 19],
    ['name' => 'Ouidah II', 'commune_id' => 19],
    ['name' => 'Ouidah III', 'commune_id' => 19],
    ['name' => 'Ouidah IV', 'commune_id' => 19],
    ['name' => 'Pahou', 'commune_id' => 19],
    ['name' => 'Savi', 'commune_id' => 19],
    ['name' => 'Ahomey-Lokpo', 'commune_id' => 20],
    ['name' => 'Dékanmey', 'commune_id' => 20],
    ['name' => 'Ganvié I', 'commune_id' => 20],
    ['name' => 'Ganvié II', 'commune_id' => 20],
    ['name' => 'Houédo-Aguékon', 'commune_id' => 20],
    ['name' => 'Sô-Ava', 'commune_id' => 20],
    ['name' => 'Vekky', 'commune_id' => 20],
    ['name' => 'Agué', 'commune_id' => 21],
    ['name' => 'Colli-Agbamè', 'commune_id' => 21],
    ['name' => 'Coussi', 'commune_id' => 21],
    ['name' => 'Damè', 'commune_id' => 21],
    ['name' => 'Djanglanmè', 'commune_id' => 21],
    ['name' => 'Houègbo', 'commune_id' => 21],
    ['name' => 'Kpomè', 'commune_id' => 21],
    ['name' => 'Sè', 'commune_id' => 21],
    ['name' => 'Sèhouè', 'commune_id' => 21],
    ['name' => 'Toffo-Agué', 'commune_id' => 21],
    ['name' => 'Avamè', 'commune_id' => 22],
    ['name' => 'Azohouè-Aliho', 'commune_id' => 22],
    ['name' => 'Azohouè-Cada', 'commune_id' => 22],
    ['name' => 'Tori-Bossito', 'commune_id' => 22],
    ['name' => 'Tori-Cada', 'commune_id' => 22],
    ['name' => 'Tori-Gare', 'commune_id' => 22],
    ['name' => 'Tori-Aïdohoué', 'commune_id' => 22],
    ['name' => 'Tori-Acadjamè', 'commune_id' => 22],
    ['name' => 'Adjan', 'commune_id' => 23],
    ['name' => 'Dawè', 'commune_id' => 23],
    ['name' => 'Djigbé', 'commune_id' => 23],
    ['name' => 'Dodji-Bata', 'commune_id' => 23],
    ['name' => 'Hèkanmé', 'commune_id' => 23],
    ['name' => 'Koundokpoé', 'commune_id' => 23],
    ['name' => 'Sèdjè-Dénou', 'commune_id' => 23],
    ['name' => 'Sèdjè-Houégoudo', 'commune_id' => 23],
    ['name' => 'Tangbo-Djevié', 'commune_id' => 23],
    ['name' => 'Yokpo', 'commune_id' => 23],
    ['name' => 'Zè', 'commune_id' => 23],
    ['name' => 'Bembéréké', 'commune_id' => 24],
    ['name' => 'Béroubouay', 'commune_id' => 24],
    ['name' => 'Bouanri', 'commune_id' => 24],
    ['name' => 'Gamia', 'commune_id' => 24],
    ['name' => 'Ina', 'commune_id' => 24],
    ['name' => 'Basso', 'commune_id' => 25],
    ['name' => 'Bouka', 'commune_id' => 25],
    ['name' => 'Dérassi', 'commune_id' => 25],
    ['name' => 'Dunkassa', 'commune_id' => 25],
    ['name' => 'Kalalé', 'commune_id' => 25],
    ['name' => 'Péonga', 'commune_id' => 25],
    ['name' => 'Bori', 'commune_id' => 26],
    ['name' => 'Gbégourou', 'commune_id' => 26],
    ['name' => 'N\'Dali', 'commune_id' => 26],
    ['name' => 'Ouénou', 'commune_id' => 26],
    ['name' => 'Sirarou', 'commune_id' => 26],
    ['name' => 'Biro', 'commune_id' => 27],
    ['name' => 'Gnonkourakali', 'commune_id' => 27],
    ['name' => 'Nikki', 'commune_id' => 27],
    ['name' => 'Ouénou', 'commune_id' => 27],
    ['name' => 'Sérékalé', 'commune_id' => 27],
    ['name' => 'Suya', 'commune_id' => 27],
    ['name' => 'Tasso', 'commune_id' => 27],
    ['name' => '1er arrondissement de Parakou', 'commune_id' => 28],
    ['name' => '2e arrondissement de Parakou', 'commune_id' => 28],
    ['name' => '3e arrondissement de Parakou', 'commune_id' => 28],
    ['name' => 'Gninsy', 'commune_id' => 29],
    ['name' => 'Guinagourou', 'commune_id' => 29],
    ['name' => 'Kpané', 'commune_id' => 29],
    ['name' => 'Pébié', 'commune_id' => 29],
    ['name' => 'Pèrèrè', 'commune_id' => 29],
    ['name' => 'Sontou', 'commune_id' => 29],
    ['name' => 'Fô-Bourè', 'commune_id' => 30],
    ['name' => 'Sèkèrè', 'commune_id' => 30],
    ['name' => 'Sikki', 'commune_id' => 30],
    ['name' => 'Sinendé', 'commune_id' => 30],
    ['name' => 'Alafiarou', 'commune_id' => 31],
    ['name' => 'Bétérou', 'commune_id' => 31],
    ['name' => 'Goro', 'commune_id' => 31],
    ['name' => 'Kika', 'commune_id' => 31],
    ['name' => 'Sanson', 'commune_id' => 31],
    ['name' => 'Tchaourou', 'commune_id' => 31],
    ['name' => 'Tchatchou', 'commune_id' => 31],
    ['name' => 'Agoua', 'commune_id' => 32],
    ['name' => 'Akpassi', 'commune_id' => 32],
    ['name' => 'Atokoligbé', 'commune_id' => 32],
    ['name' => 'Bantè', 'commune_id' => 32],
    ['name' => 'Bobè', 'commune_id' => 32],
    ['name' => 'Gouka', 'commune_id' => 32],
    ['name' => 'Koko', 'commune_id' => 32],
    ['name' => 'Lougba', 'commune_id' => 32],
    ['name' => 'Pira', 'commune_id' => 32],
    ['name' => 'Akofodjoulè', 'commune_id' => 33],
    ['name' => 'Dassa I', 'commune_id' => 33],
    ['name' => 'Dassa II', 'commune_id' => 33],
    ['name' => 'Gbaffo', 'commune_id' => 33],
    ['name' => 'Kerè', 'commune_id' => 33],
    ['name' => 'Kpingni', 'commune_id' => 33],
    ['name' => 'Lèma', 'commune_id' => 33],
    ['name' => 'Paouignan', 'commune_id' => 33],
    ['name' => 'Soclogbo', 'commune_id' => 33],
    ['name' => 'Tré', 'commune_id' => 33],
    ['name' => 'Aklankpa', 'commune_id' => 34],
    ['name' => 'Assanté', 'commune_id' => 34],
    ['name' => 'Glazoué', 'commune_id' => 34],
    ['name' => 'Gomè', 'commune_id' => 34],
    ['name' => 'Kpakpaza', 'commune_id' => 34],
    ['name' => 'Magoumi', 'commune_id' => 34],
    ['name' => 'Ouèdèmè', 'commune_id' => 34],
    ['name' => 'Sokponta', 'commune_id' => 34],
    ['name' => 'Thio', 'commune_id' => 34],
    ['name' => 'Zaffé', 'commune_id' => 34],
    ['name' => 'Challa-Ogoi', 'commune_id' => 35],
    ['name' => 'Djègbè', 'commune_id' => 35],
    ['name' => 'Gbanlin', 'commune_id' => 35],
    ['name' => 'Kémon', 'commune_id' => 35],
    ['name' => 'Kilibo', 'commune_id' => 35],
    ['name' => 'Laminou', 'commune_id' => 35],
    ['name' => 'Odougba', 'commune_id' => 35],
    ['name' => 'Ouèssè', 'commune_id' => 35],
    ['name' => 'Toui', 'commune_id' => 35],
    ['name' => 'Djaloukou', 'commune_id' => 36],
    ['name' => 'Doumè', 'commune_id' => 36],
    ['name' => 'Gobada', 'commune_id' => 36],
    ['name' => 'Kpataba', 'commune_id' => 36],
    ['name' => 'Lahotan', 'commune_id' => 36],
    ['name' => 'Lèma', 'commune_id' => 36],
    ['name' => 'Logozohè', 'commune_id' => 36],
    ['name' => 'Monkpa', 'commune_id' => 36],
    ['name' => 'Ottola', 'commune_id' => 36],
    ['name' => 'Ouèssè', 'commune_id' => 36],
    ['name' => 'Savalou-aga', 'commune_id' => 36],
    ['name' => 'Savalou-agbado', 'commune_id' => 36],
    ['name' => 'Savalou-attakè', 'commune_id' => 36],
    ['name' => 'Tchetti', 'commune_id' => 36],
    ['name' => 'Adido', 'commune_id' => 37],
    ['name' => 'Bèssè', 'commune_id' => 37],
    ['name' => 'Boni', 'commune_id' => 37],
    ['name' => 'Kaboua', 'commune_id' => 37],
    ['name' => 'Ofè', 'commune_id' => 37],
    ['name' => 'Okpara', 'commune_id' => 37],
    ['name' => 'Plateau', 'commune_id' => 37],
    ['name' => 'Sakin', 'commune_id' => 37],
    ['name' => 'Aplahoué', 'commune_id' => 38],
    ['name' => 'Atomè', 'commune_id' => 38],
    ['name' => 'Azovè', 'commune_id' => 38],
    ['name' => 'Dekpo', 'commune_id' => 38],
    ['name' => 'Godohou', 'commune_id' => 38],
    ['name' => 'Kissamey', 'commune_id' => 38],
    ['name' => 'Lonkly', 'commune_id' => 38],
    ['name' => 'Adjintimey', 'commune_id' => 39],
    ['name' => 'Bètoumey', 'commune_id' => 39],
    ['name' => 'Djakotomey I', 'commune_id' => 39],
    ['name' => 'Djakotomey II', 'commune_id' => 39],
    ['name' => 'Gohomey', 'commune_id' => 39],
    ['name' => 'Houègamey', 'commune_id' => 39],
    ['name' => 'Kinkinhoué', 'commune_id' => 39],
    ['name' => 'Kokohoué', 'commune_id' => 39],
    ['name' => 'Kpoba', 'commune_id' => 39],
    ['name' => 'Sokouhoué', 'commune_id' => 39],
    ['name' => 'Ayomi', 'commune_id' => 40],
    ['name' => 'Dèvè', 'commune_id' => 40],
    ['name' => 'Honton', 'commune_id' => 40],
    ['name' => 'Lokogohoué', 'commune_id' => 40],
    ['name' => 'Madjrè', 'commune_id' => 40],
    ['name' => 'Tota', 'commune_id' => 40],
    ['name' => 'Totchagni', 'commune_id' => 40],
    ['name' => 'Adjanhonmè', 'commune_id' => 41],
    ['name' => 'Ahogbèya', 'commune_id' => 41],
    ['name' => 'Aya-Hohoué', 'commune_id' => 41],
    ['name' => 'Djotto', 'commune_id' => 41],
    ['name' => 'Hondji', 'commune_id' => 41],
    ['name' => 'Klouékanmè', 'commune_id' => 41],
    ['name' => 'Lanta', 'commune_id' => 41],
    ['name' => 'Tchikpé', 'commune_id' => 41],
    ['name' => 'Adoukandji', 'commune_id' => 42],
    ['name' => 'Ahondjinnako', 'commune_id' => 42],
    ['name' => 'Ahomadegbe', 'commune_id' => 42],
    ['name' => 'Banigbé', 'commune_id' => 42],
    ['name' => 'Gnizounmè', 'commune_id' => 42],
    ['name' => 'Hlassamè', 'commune_id' => 42],
    ['name' => 'Lalo', 'commune_id' => 42],
    ['name' => 'Lokogba', 'commune_id' => 42],
    ['name' => 'Tchito', 'commune_id' => 42],
    ['name' => 'Tohou', 'commune_id' => 42],
    ['name' => 'Zalli', 'commune_id' => 42],
    ['name' => 'Adjido', 'commune_id' => 43],
    ['name' => 'Avédjin', 'commune_id' => 43],
    ['name' => 'Doko', 'commune_id' => 43],
    ['name' => 'Houédogli', 'commune_id' => 43],
    ['name' => 'Missinko', 'commune_id' => 43],
    ['name' => 'Tannou-Gola', 'commune_id' => 43],
    ['name' => 'Toviklin', 'commune_id' => 43],
    ['name' => 'Alédjo', 'commune_id' => 44],
    ['name' => 'Bassila', 'commune_id' => 44],
    ['name' => 'Manigri', 'commune_id' => 44],
    ['name' => 'Pénéssoulou', 'commune_id' => 44],
    ['name' => 'Anandana', 'commune_id' => 45],
    ['name' => 'Copargo', 'commune_id' => 45],
    ['name' => 'Pabégou', 'commune_id' => 45],
    ['name' => 'Singré', 'commune_id' => 45],
    ['name' => 'Barei', 'commune_id' => 46],
    ['name' => 'Bariénou', 'commune_id' => 46],
    ['name' => 'Bélléfoungou', 'commune_id' => 46],
    ['name' => 'Bougou', 'commune_id' => 46],
    ['name' => 'Djougou I', 'commune_id' => 46],
    ['name' => 'Djougou II', 'commune_id' => 46],
    ['name' => 'Djougou III', 'commune_id' => 46],
    ['name' => 'Kolokondé', 'commune_id' => 46],
    ['name' => 'Onklou', 'commune_id' => 46],
    ['name' => 'Patargo', 'commune_id' => 46],
    ['name' => 'Pélébina', 'commune_id' => 46],
    ['name' => 'Sérou', 'commune_id' => 46],
    ['name' => 'Badjoudè', 'commune_id' => 47],
    ['name' => 'Kondé', 'commune_id' => 47],
    ['name' => 'Ouaké', 'commune_id' => 47],
    ['name' => 'Sèmèrè I', 'commune_id' => 47],
    ['name' => 'Sèmèrè II', 'commune_id' => 47],
    ['name' => 'Tchalinga', 'commune_id' => 47],
    ['name' => '1er arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '2e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '3e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '4e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '5e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '6e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '7e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '8e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '9e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '10e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '11e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '12e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => '13e arrondissement de Cotonou', 'commune_id' => 48],
    ['name' => 'Adohoun', 'commune_id' => 49],
    ['name' => 'Atchannou', 'commune_id' => 49],
    ['name' => 'Athiémé', 'commune_id' => 49],
    ['name' => 'Dédékpoé', 'commune_id' => 49],
    ['name' => 'Kpinnou', 'commune_id' => 49],
    ['name' => 'Agbodji', 'commune_id' => 50],
    ['name' => 'Badazoui', 'commune_id' => 50],
    ['name' => 'Bopa', 'commune_id' => 50],
    ['name' => 'Gbakpodji', 'commune_id' => 50],
    ['name' => 'Lobogo', 'commune_id' => 50],
    ['name' => 'Possotomè', 'commune_id' => 50],
    ['name' => 'Yégodoé', 'commune_id' => 50],
    ['name' => 'Agatogbo', 'commune_id' => 51],
    ['name' => 'Akodéha', 'commune_id' => 51],
    ['name' => 'Comè', 'commune_id' => 51],
    ['name' => 'Ouèdèmè-Pédah', 'commune_id' => 51],
    ['name' => 'Oumako', 'commune_id' => 51],
    ['name' => 'Adjaha', 'commune_id' => 52],
    ['name' => 'Agoué', 'commune_id' => 52],
    ['name' => 'Avloh', 'commune_id' => 52],
    ['name' => 'Djanglanmey', 'commune_id' => 52],
    ['name' => 'Gbéhoué', 'commune_id' => 52],
    ['name' => 'Grand-Popo', 'commune_id' => 52],
    ['name' => 'Sazoué', 'commune_id' => 52],
    ['name' => 'Dahé', 'commune_id' => 53],
    ['name' => 'Doutou', 'commune_id' => 53],
    ['name' => 'Honhoué', 'commune_id' => 53],
    ['name' => 'Houéyogbé', 'commune_id' => 53],
    ['name' => 'Sè', 'commune_id' => 53],
    ['name' => 'Zoungbonou', 'commune_id' => 53],
    ['name' => 'Agamé', 'commune_id' => 54],
    ['name' => 'Houin', 'commune_id' => 54],
    ['name' => 'Koudo', 'commune_id' => 54],
    ['name' => 'Lokossa', 'commune_id' => 54],
    ['name' => 'Ouèdèmè', 'commune_id' => 54],
    ['name' => 'Adjarra I', 'commune_id' => 55],
    ['name' => 'Adjarra II', 'commune_id' => 55],
    ['name' => 'Aglogbé', 'commune_id' => 55],
    ['name' => 'Honvié', 'commune_id' => 55],
    ['name' => 'Malanhoui', 'commune_id' => 55],
    ['name' => 'Médédjonou', 'commune_id' => 55],
    ['name' => 'Adjohoun', 'commune_id' => 56],
    ['name' => 'Akpadanou', 'commune_id' => 56],
    ['name' => 'Awonou', 'commune_id' => 56],
    ['name' => 'Azowlissè', 'commune_id' => 56],
    ['name' => 'Dèmè', 'commune_id' => 56],
    ['name' => 'Gangban', 'commune_id' => 56],
    ['name' => 'Kodè', 'commune_id' => 56],
    ['name' => 'Togbota', 'commune_id' => 56],
    ['name' => 'Avagbodji', 'commune_id' => 57],
    ['name' => 'Houédomè', 'commune_id' => 57],
    ['name' => 'Zoungamè', 'commune_id' => 57],
    ['name' => 'Akpro-Missérété', 'commune_id' => 58],
    ['name' => 'Gomè-Sota', 'commune_id' => 58],
    ['name' => 'Katagon', 'commune_id' => 58],
    ['name' => 'Vakon', 'commune_id' => 58],
    ['name' => 'Zodogbomey', 'commune_id' => 58],
    ['name' => 'Atchoukpa', 'commune_id' => 59],
    ['name' => 'Avrankou', 'commune_id' => 59],
    ['name' => 'Djomon', 'commune_id' => 59],
    ['name' => 'Gbozounmè', 'commune_id' => 59],
    ['name' => 'Kouty', 'commune_id' => 59],
    ['name' => 'Ouanho', 'commune_id' => 59],
    ['name' => 'Sado', 'commune_id' => 59],
    ['name' => 'Affamè', 'commune_id' => 60],
    ['name' => 'Atchonsa', 'commune_id' => 60],
    ['name' => 'Bonou', 'commune_id' => 60],
    ['name' => 'Damè-Wogon', 'commune_id' => 60],
    ['name' => 'Houinviguè', 'commune_id' => 60],
    ['name' => 'Dangbo', 'commune_id' => 61],
    ['name' => 'Dèkin', 'commune_id' => 61],
    ['name' => 'Gbéko', 'commune_id' => 61],
    ['name' => 'Houédomey', 'commune_id' => 61],
    ['name' => 'Hozin', 'commune_id' => 61],
    ['name' => 'Késsounou', 'commune_id' => 61],
    ['name' => 'Zounguè', 'commune_id' => 61],
    ['name' => '1er arrondissement', 'commune_id' => 62],
    ['name' => '2e arrondissement', 'commune_id' => 62],
    ['name' => '3e arrondissement', 'commune_id' => 62],
    ['name' => '4e arrondissement', 'commune_id' => 62],
    ['name' => '5e arrondissement', 'commune_id' => 62],
    ['name' => 'Agblangandan', 'commune_id' => 63],
    ['name' => 'Aholouyèmè', 'commune_id' => 63],
    ['name' => 'Djèrègbè', 'commune_id' => 63],
    ['name' => 'Ekpè', 'commune_id' => 63],
    ['name' => 'Sèmè-Kpodji', 'commune_id' => 63],
    ['name' => 'Tohouè', 'commune_id' => 63],
    ['name' => 'Adja-Ouèrè', 'commune_id' => 64],
    ['name' => 'Ikpinlè', 'commune_id' => 64],
    ['name' => 'Kpoulou', 'commune_id' => 64],
    ['name' => 'Massè', 'commune_id' => 64],
    ['name' => 'Oko-Akarè', 'commune_id' => 64],
    ['name' => 'Totonnoukon', 'commune_id' => 64],
    ['name' => 'Banigbé', 'commune_id' => 65],
    ['name' => 'Daagbé', 'commune_id' => 65],
    ['name' => 'Ifangni', 'commune_id' => 65],
    ['name' => 'Ko-Koumolou', 'commune_id' => 65],
    ['name' => 'Lagbé', 'commune_id' => 65],
    ['name' => 'Tchaada', 'commune_id' => 65],
    ['name' => 'Adakplamé', 'commune_id' => 66],
    ['name' => 'Idigny', 'commune_id' => 66],
    ['name' => 'Kpankou', 'commune_id' => 66],
    ['name' => 'Kétou', 'commune_id' => 66],
    ['name' => 'Odometa', 'commune_id' => 66],
    ['name' => 'Okpometa', 'commune_id' => 66],
    ['name' => 'Ahoyéyé', 'commune_id' => 67],
    ['name' => 'Igana', 'commune_id' => 67],
    ['name' => 'Issaba', 'commune_id' => 67],
    ['name' => 'Pobè', 'commune_id' => 67],
    ['name' => 'Towé', 'commune_id' => 67],
    ['name' => 'Aguidi', 'commune_id' => 68],
    ['name' => 'Ita-Djèbou', 'commune_id' => 68],
    ['name' => 'Sakété I', 'commune_id' => 68],
    ['name' => 'Sakété II', 'commune_id' => 68],
    ['name' => 'Takon', 'commune_id' => 68],
    ['name' => 'Yoko', 'commune_id' => 68],
    ['name' => 'Agbokpa', 'commune_id' => 69],
    ['name' => 'Dètohou', 'commune_id' => 69],
    ['name' => 'Djègbè', 'commune_id' => 69],
    ['name' => 'Hounli', 'commune_id' => 69],
    ['name' => 'Sèhoun', 'commune_id' => 69],
    ['name' => 'Vidolè', 'commune_id' => 69],
    ['name' => 'Zounzounmè', 'commune_id' => 69],
    ['name' => 'Adahondjigon', 'commune_id' => 70],
    ['name' => 'Adingningon', 'commune_id' => 70],
    ['name' => 'Agbangnizoun', 'commune_id' => 70],
    ['name' => 'Kinta', 'commune_id' => 70],
    ['name' => 'Kpota', 'commune_id' => 70],
    ['name' => 'Lissazounmè', 'commune_id' => 70],
    ['name' => 'Sahé', 'commune_id' => 70],
    ['name' => 'Siwé', 'commune_id' => 70],
    ['name' => 'Tanvé', 'commune_id' => 70],
    ['name' => 'Zoungoudo', 'commune_id' => 70],
    ['name' => 'Agongointo', 'commune_id' => 71],
    ['name' => 'Avogbanna', 'commune_id' => 71],
    ['name' => 'Bohicon I', 'commune_id' => 71],
    ['name' => 'Bohicon II', 'commune_id' => 71],
    ['name' => 'Gnidjazoun', 'commune_id' => 71],
    ['name' => 'Lissèzoun', 'commune_id' => 71],
    ['name' => 'Ouassaho', 'commune_id' => 71],
    ['name' => 'Passagon', 'commune_id' => 71],
    ['name' => 'Saclo', 'commune_id' => 71],
    ['name' => 'Sodohomè', 'commune_id' => 71],
    ['name' => 'Adogbé', 'commune_id' => 72],
    ['name' => 'Gounli', 'commune_id' => 72],
    ['name' => 'Houéko', 'commune_id' => 72],
    ['name' => 'Houen-Hounso', 'commune_id' => 72],
    ['name' => 'Lainta-Cogbè', 'commune_id' => 72],
    ['name' => 'Naogon', 'commune_id' => 72],
    ['name' => 'Soli', 'commune_id' => 72],
    ['name' => 'Zogba', 'commune_id' => 72],
    ['name' => 'Agondji', 'commune_id' => 73],
    ['name' => 'Agouna', 'commune_id' => 73],
    ['name' => 'Dan', 'commune_id' => 73],
    ['name' => 'Djidja', 'commune_id' => 73],
    ['name' => 'Dohouimè', 'commune_id' => 73],
    ['name' => 'Gobaix', 'commune_id' => 73],
    ['name' => 'Monsourou', 'commune_id' => 73],
    ['name' => 'Mougnon', 'commune_id' => 73],
    ['name' => 'Oungbègamè', 'commune_id' => 73],
    ['name' => 'Houto', 'commune_id' => 73],
    ['name' => 'Setto', 'commune_id' => 73],
    ['name' => 'Zoukon', 'commune_id' => 73],
    ['name' => 'Dasso', 'commune_id' => 74],
    ['name' => 'Ouinhi', 'commune_id' => 74],
    ['name' => 'Sagon', 'commune_id' => 74],
    ['name' => 'Tohoué', 'commune_id' => 74],
    ['name' => 'Allahé', 'commune_id' => 75],
    ['name' => 'Assalin', 'commune_id' => 75],
    ['name' => 'Houngomey', 'commune_id' => 75],
    ['name' => 'Kpakpamè', 'commune_id' => 75],
    ['name' => 'Kpozoun', 'commune_id' => 75],
    ['name' => 'Za-Kpota', 'commune_id' => 75],
    ['name' => 'Za-Tanta', 'commune_id' => 75],
    ['name' => 'Zèko', 'commune_id' => 75],
    ['name' => 'Agonli-Houégbo', 'commune_id' => 76],
    ['name' => 'Banamè', 'commune_id' => 76],
    ['name' => 'N\'-Tan', 'commune_id' => 76],
    ['name' => 'Dovi', 'commune_id' => 76],
    ['name' => 'Kpédékpo', 'commune_id' => 76],
    ['name' => 'Zagnanado', 'commune_id' => 76],
    ['name' => 'Akiza', 'commune_id' => 77],
    ['name' => 'Avlamè', 'commune_id' => 77],
    ['name' => 'Cana I', 'commune_id' => 77],
    ['name' => 'Cana II', 'commune_id' => 77],
    ['name' => 'Domè', 'commune_id' => 77],
    ['name' => 'Koussoukpa', 'commune_id' => 77],
    ['name' => 'Kpokissa', 'commune_id' => 77],
    ['name' => 'Massi', 'commune_id' => 77],
    ['name' => 'Tanwé-Hessou', 'commune_id' => 77],
    ['name' => 'Zogbodomey', 'commune_id' => 77],
    ['name' => 'Zoukou', 'commune_id' => 77],
        ]);
    }
}
